{
 "title": "Minar Health Stats (Power, Temperature, Fan-Speed)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Core Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_0" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_1" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_2" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "core_temp_Core_3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA GPU Power Consumption (Watts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All GPU Temperatures (℉)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All GPU Fan-Speeds   (unit=%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0_fan1",
     "select": [
      [
       { "params": [ "gpu" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1_fan1",
     "select": [
      [
       { "params": [ "gpu" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2_fan1",
     "select": [
      [
       { "params": [ "gpu" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3_fan1",
     "select": [
      [
       { "params": [ "gpu" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.0",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.1",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.2",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.3",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.4",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  6",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.5",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  7",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.6",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVIDIA  8",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "nvidia.gpu.7",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_0",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_1",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_2",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMD 4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "amd_3",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}