{
 "title": "Miner Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu0power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu1power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu2power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu3power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu4power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu5power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu6power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu7power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Heat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu0heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu1heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu2heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu3heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu4heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu5heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu6heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu7heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu0power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu0heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu1power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu1heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu2power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu2heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu3power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu3heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu4power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu4heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu5power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu5heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 6",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu6power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu6heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU 7",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gpu7power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "gpu7heat",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}